# Prompt templates for classification processing

prompts:
  assistant_instructions_json:
    template: |
      Leia atentamente o conteúdo do campo 'entry_content'.

      Primeiro, procure por pistas explícitas de classificação no início do texto (ex.: etiquetas como "agenda:", "diario:", "tarefas:", etc.).  
      Se não houver pista clara no início, avalie o conteúdo e use os seguintes apontamentos para classificar:

      Palavras-chave por categoria:
      - diario: sentimentos, reflexão, pensei, senti, vivi, memória, desabafo, sonho
      - agenda: reunião, compromisso, encontro, evento, agendar, marcar, prazo, horário
      - tarefas: fazer, concluir, terminar, iniciar, projeto, objetivo, meta, planejar
      - contas: despesa, gasto, investi, paguei, cobrei, fatura, recibo, saldo, transferi
      - contactos: telefone, email, contato, número, endereço, comunicação, ligação
      - entidades: empresa, serviço, instituição, site, loja, marca, organização

      Para cada contexto identificado:
      1. Apenas uma categoria por contexto.
      2. Ignore erros ortográficos se o significado for claro.
      3. Priorize categorias conforme esta ordem em caso de dúvida:
        agenda > diario > contas > tarefas > contactos > entidades
      4. Se tarefa e evento coexistirem, classifique como 'agenda'.
      5. Não classifique como 'contactos' apenas por citar nomes — é necessário telefone, email ou relação funcional.
      6. Não considere locais genéricos ou fictícios como 'entidades'.

      Formato de resposta:
      {
        "classifications": [
          {"text": "texto extraído", "category": "categoria"}
        ]
      }

      Responda somente com JSON válido, sem comentários, repetições ou explicações.  
      Use aspas duplas para envolver todos os textos extraídos.

 
  parse_entry_prompt:
    template: |
      "Leia com atenção o seguinte conteúdo e separe-o em diferentes contextos e classifica-os."
      "A entry_content poderá conter informação relativa a classificação, como por exemplo: 'agenda', 'diario', 'tarefas', 'contas', 'contactos', 'entidades'; usar essa informação para ajudar a classificar o conteúdo.\n"
      "Atenção que, se existir uma tarefa, normalmente há (com exceções) um evento associado\n"
      "esteja atento a múltiplas etiquetas numa só frase\n 
        - ex: Esta manhã acordei às 7h, fui tomar o pequeno-almoço e gastei 10 euros no pequeno-almoço. tem as tags diario e contas\n\n"
      "Texto: {entry_content}"
